export type AirlineCategory = "low-cost" | "leisure" | "hybrid" | "flag-carrier";
export type AirlineSourceConfidence = "unofficial" | "search-only" | "official" | "official-test";

export type AirlineDefinition = {
  id: string;
  name: string;
  iataCodes: string[];
  category: AirlineCategory;
  websiteUrl: string;
  sourceConfidenceDefault: AirlineSourceConfidence;
  supportsPricedAdapter: boolean;
  supportsSearchLink: boolean;
  supportsExactDeepLink: boolean;
  notes?: string;
};

export const AIRLINES: AirlineDefinition[] = [
  {
    id: "ryanair",
    name: "Ryanair",
    iataCodes: ["FR"],
    category: "low-cost",
    websiteUrl: "https://www.ryanair.com/cz/cs",
    sourceConfidenceDefault: "unofficial",
    supportsPricedAdapter: true,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "Priced unofficial adapter exists via public fare-finder endpoint.",
  },
  {
    id: "wizz",
    name: "Wizz Air",
    iataCodes: ["W6"],
    category: "low-cost",
    websiteUrl: "https://wizzair.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "No stable public priced endpoint found. Homepage verification only.",
  },
  {
    id: "eurowings",
    name: "Eurowings",
    iataCodes: ["EW"],
    category: "low-cost",
    websiteUrl: "https://www.eurowings.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
  },
  {
    id: "vueling",
    name: "Vueling",
    iataCodes: ["VY"],
    category: "low-cost",
    websiteUrl: "https://www.vueling.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
  },
  {
    id: "easyjet",
    name: "easyJet",
    iataCodes: ["U2", "EJU", "EC"],
    category: "low-cost",
    websiteUrl: "https://www.easyjet.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
  },
  {
    id: "smartwings",
    name: "Smartwings",
    iataCodes: ["QS"],
    category: "leisure",
    websiteUrl: "https://www.smartwings.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "Czech charter/leisure carrier. Flies mainly in summer from CZ airports.",
  },
  {
    id: "pegasus",
    name: "Pegasus",
    iataCodes: ["PC"],
    category: "low-cost",
    websiteUrl: "https://www.flypgs.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "Turkish low-cost. Strong from VIE and PRG to Turkey, Greece.",
  },
  {
    id: "sunexpress",
    name: "SunExpress",
    iataCodes: ["XQ"],
    category: "leisure",
    websiteUrl: "https://www.sunexpress.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "Leisure carrier for Turkey and Mediterranean. Seasonal from PRG/VIE.",
  },
  {
    id: "transavia",
    name: "Transavia",
    iataCodes: ["HV", "TO"],
    category: "low-cost",
    websiteUrl: "https://www.transavia.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
  },
  {
    id: "norwegian",
    name: "Norwegian",
    iataCodes: ["DY", "D8"],
    category: "low-cost",
    websiteUrl: "https://www.norwegian.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
  },
  {
    id: "volotea",
    name: "Volotea",
    iataCodes: ["V7"],
    category: "low-cost",
    websiteUrl: "https://www.volotea.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
  },
  {
    id: "airbaltic",
    name: "airBaltic",
    iataCodes: ["BT"],
    category: "hybrid",
    websiteUrl: "https://www.airbaltic.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
  },
  {
    id: "ajet",
    name: "AJet",
    iataCodes: ["VF"],
    category: "low-cost",
    websiteUrl: "https://www.ajet.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "Formerly AnadoluJet. Turkish low-cost, flies from PRG/VIE to Turkey.",
  },
  {
    id: "corendon",
    name: "Corendon",
    iataCodes: ["XC", "CD", "XR"],
    category: "leisure",
    websiteUrl: "https://www.corendonairlines.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "Dutch/Turkish leisure carrier. Charter flights to Turkey, Egypt, Canaries.",
  },
  {
    id: "aircairo",
    name: "Air Cairo",
    iataCodes: ["SM"],
    category: "leisure",
    websiteUrl: "https://aircairo.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "Egyptian leisure carrier to Hurghada, Marsa Alam, Sharm. Seasonal charter.",
  },
  {
    id: "condor",
    name: "Condor",
    iataCodes: ["DE"],
    category: "leisure",
    websiteUrl: "https://www.condor.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "German leisure carrier. Long-haul and Mediterranean/Canaries.",
  },
  {
    id: "jet2",
    name: "Jet2",
    iataCodes: ["LS"],
    category: "low-cost",
    websiteUrl: "https://www.jet2.com",
    sourceConfidenceDefault: "search-only",
    supportsPricedAdapter: false,
    supportsSearchLink: true,
    supportsExactDeepLink: false,
    notes: "UK leisure low-cost. Limited presence in CZ market.",
  },
];

export const AIRLINE_BY_ID = new Map(AIRLINES.map((a) => [a.id, a]));
export const AIRLINE_BY_IATA = new Map(AIRLINES.flatMap((a) => a.iataCodes.map((code) => [code, a])));
