import type { ItineraryOption } from "./types";

type MockTripSeed = Omit<
  ItineraryOption,
  | "availabilityStatus"
  | "availabilityNote"
  | "deepLink"
  | "inboundSegments"
  | "isReturn"
  | "linkNote"
  | "linkType"
  | "outboundSegments"
  | "passengers"
  | "priceStatus"
  | "provider"
  | "segments"
  | "sourceUrl"
  | "weatherConfidence"
> &
  Partial<Pick<ItineraryOption, "isReturn" | "passengers">>;

const mockTripSeeds: MockTripSeed[] = [
  {
    id: "tenerife-prg-nov-5n",
    destination: "Tenerife",
    country: "Kanárské ostrovy",
    destinationAirportCode: "TFS",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 22,
    month: 11,
    dates: { depart: "2026-11-12", return: "2026-11-17" },
    nights: 5,
    origin: "PRG",
    totalPrice: 6890,
    currency: "CZK",
    airline: "Smartwings",
    source: "Mock",
    departureTime: "10:15",
    returnTime: "18:25",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 72,
    destinationValue: 94,
    reliability: 84,
  },
  {
    id: "gran-canaria-vie-nov-5n",
    destination: "Gran Canaria",
    country: "Kanárské ostrovy",
    destinationAirportCode: "LPA",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 23,
    month: 11,
    dates: { depart: "2026-11-08", return: "2026-11-13" },
    nights: 5,
    origin: "VIE",
    totalPrice: 6290,
    currency: "CZK",
    airline: "Ryanair",
    source: "Ryanair",
    departureTime: "07:50",
    returnTime: "16:40",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 76,
    destinationValue: 93,
    reliability: 86,
  },
  {
    id: "malaga-prg-nov-4n",
    destination: "Málaga",
    country: "Španělsko",
    destinationAirportCode: "AGP",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 18,
    month: 11,
    dates: { depart: "2026-11-19", return: "2026-11-23" },
    nights: 4,
    origin: "PRG",
    totalPrice: 5190,
    currency: "CZK",
    airline: "Ryanair",
    source: "Ryanair",
    departureTime: "09:35",
    returnTime: "17:10",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 88,
    destinationValue: 88,
    reliability: 82,
  },
  {
    id: "madeira-vie-nov-6n",
    destination: "Madeira",
    country: "Portugalsko",
    destinationAirportCode: "FNC",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 20,
    month: 11,
    dates: { depart: "2026-11-15", return: "2026-11-21" },
    nights: 6,
    origin: "VIE",
    totalPrice: 7980,
    currency: "CZK",
    airline: "Austrian + TAP",
    source: "Kiwi",
    departureTime: "12:40",
    returnTime: "19:00",
    baggageIncluded: ["backpack", "cabin"],
    direct: false,
    layoverHours: 2.2,
    weekendFit: 64,
    destinationValue: 92,
    reliability: 78,
  },
  {
    id: "larnaca-prg-nov-4n",
    destination: "Larnaka",
    country: "Kypr",
    destinationAirportCode: "LCA",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 21,
    month: 11,
    dates: { depart: "2026-11-05", return: "2026-11-09" },
    nights: 4,
    origin: "PRG",
    totalPrice: 5790,
    currency: "CZK",
    airline: "Wizz Air",
    source: "Skyscanner",
    departureTime: "11:20",
    returnTime: "19:45",
    baggageIncluded: ["backpack", "cabin"],
    direct: true,
    weekendFit: 94,
    destinationValue: 90,
    reliability: 84,
  },
  {
    id: "malta-ped-nov-4n",
    destination: "Malta",
    country: "Malta",
    destinationAirportCode: "MLA",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 19,
    month: 11,
    dates: { depart: "2026-11-10", return: "2026-11-14" },
    nights: 4,
    origin: "PED",
    totalPrice: 8290,
    currency: "CZK",
    airline: "Ryanair + KM Malta",
    source: "Mock",
    departureTime: "08:10",
    returnTime: "21:50",
    baggageIncluded: ["backpack"],
    direct: false,
    layoverHours: 3.5,
    weekendFit: 70,
    destinationValue: 87,
    reliability: 70,
  },
  {
    id: "malaga-ped-nov-4n",
    destination: "Málaga",
    country: "Španělsko",
    destinationAirportCode: "AGP",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 18,
    month: 11,
    dates: { depart: "2026-11-22", return: "2026-11-26" },
    nights: 4,
    origin: "PED",
    totalPrice: 7600,
    currency: "CZK",
    airline: "Smartwings + Ryanair",
    source: "Mock",
    departureTime: "13:20",
    returnTime: "20:10",
    baggageIncluded: ["backpack"],
    direct: false,
    layoverHours: 4,
    weekendFit: 63,
    destinationValue: 85,
    reliability: 68,
  },
  {
    id: "malaga-prg-jun-4n",
    destination: "Málaga",
    country: "Španělsko",
    destinationAirportCode: "AGP",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 27,
    month: 6,
    dates: { depart: "2026-06-12", return: "2026-06-16" },
    nights: 4,
    origin: "PRG",
    totalPrice: 4290,
    currency: "CZK",
    airline: "Ryanair",
    source: "Ryanair",
    departureTime: "09:35",
    returnTime: "17:10",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 92,
    destinationValue: 88,
    reliability: 82,
  },
  {
    id: "nice-vie-jun-3n",
    destination: "Nice",
    country: "Francie",
    destinationAirportCode: "NCE",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 25,
    month: 6,
    dates: { depart: "2026-06-05", return: "2026-06-08" },
    nights: 3,
    origin: "VIE",
    totalPrice: 5850,
    currency: "CZK",
    airline: "Wizz Air",
    source: "Skyscanner",
    departureTime: "11:20",
    returnTime: "19:45",
    baggageIncluded: ["backpack", "cabin"],
    direct: true,
    weekendFit: 97,
    destinationValue: 91,
    reliability: 86,
  },
  {
    id: "split-vie-jun-4n",
    destination: "Split",
    country: "Chorvatsko",
    destinationAirportCode: "SPU",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 26,
    month: 6,
    dates: { depart: "2026-06-20", return: "2026-06-24" },
    nights: 4,
    origin: "VIE",
    totalPrice: 3990,
    currency: "CZK",
    airline: "Austrian",
    source: "Skyscanner",
    departureTime: "05:45",
    returnTime: "14:35",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 78,
    destinationValue: 84,
    reliability: 84,
  },
  {
    id: "barcelona-prg-jun-5n",
    destination: "Barcelona",
    country: "Španělsko",
    destinationAirportCode: "BCN",
    destinationType: "cityBreak",
    destinationMode: "cityBreak",
    expectedTemperatureC: 26,
    month: 6,
    dates: { depart: "2026-06-18", return: "2026-06-23" },
    nights: 5,
    origin: "PRG",
    totalPrice: 6490,
    currency: "CZK",
    airline: "Vueling",
    source: "Kiwi",
    departureTime: "06:05",
    returnTime: "21:30",
    baggageIncluded: ["backpack", "cabin"],
    direct: true,
    weekendFit: 70,
    destinationValue: 90,
    reliability: 80,
  },
  {
    id: "copenhagen-prg-jun-2n",
    destination: "Kodaň",
    country: "Dánsko",
    destinationAirportCode: "CPH",
    destinationType: "cityBreak",
    destinationMode: "cityBreak",
    expectedTemperatureC: 19,
    month: 6,
    dates: { depart: "2026-06-19", return: "2026-06-21" },
    nights: 2,
    origin: "PRG",
    totalPrice: 3190,
    currency: "CZK",
    airline: "Norwegian",
    source: "Skyscanner",
    departureTime: "10:15",
    returnTime: "18:25",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 100,
    destinationValue: 78,
    reliability: 88,
  },
];

const fallbackSourceUrls: Record<string, string> = {
  Kiwi: "https://www.kiwi.com/",
  Mock: "https://example.com/tripwise",
  Ryanair: "https://www.ryanair.com/cz/cs",
  Skyscanner: "https://www.skyscanner.net/",
};

export const mockTrips: ItineraryOption[] = mockTripSeeds.map((trip) => ({
  ...trip,
  provider: "mock",
  passengers: trip.passengers ?? 1,
  isReturn: trip.isReturn ?? true,
  sourceUrl: fallbackSourceUrls[trip.source] ?? "https://www.google.com/travel/flights",
  deepLink: fallbackSourceUrls[trip.source] ?? "https://www.google.com/travel/flights",
  linkType: "fallback",
  linkNote: "Demo výsledek. Zdroj neumí přesný odkaz.",
  availabilityStatus: "mock",
  availabilityNote: "Demo výsledek z MVP dat. Cenu a dostupnost ověř u dopravce.",
  priceStatus: "estimated",
  weatherConfidence: "climate",
  outboundSegments: [
    {
      origin: trip.origin,
      destination: trip.destinationAirportCode,
      departureDateTime: `${trip.dates.depart}T${trip.departureTime}:00`,
      arrivalDateTime: `${trip.dates.depart}T${trip.departureTime}:00`,
      carrierName: trip.airline,
    },
  ],
  inboundSegments: [
    {
      origin: trip.destinationAirportCode,
      destination: trip.origin,
      departureDateTime: `${trip.dates.return}T${trip.returnTime}:00`,
      arrivalDateTime: `${trip.dates.return}T${trip.returnTime}:00`,
      carrierName: trip.airline,
    },
  ],
  segments: [
    {
      origin: trip.origin,
      destination: trip.destinationAirportCode,
      departureDateTime: `${trip.dates.depart}T${trip.departureTime}:00`,
      arrivalDateTime: `${trip.dates.depart}T${trip.departureTime}:00`,
      carrierName: trip.airline,
    },
    {
      origin: trip.destinationAirportCode,
      destination: trip.origin,
      departureDateTime: `${trip.dates.return}T${trip.returnTime}:00`,
      arrivalDateTime: `${trip.dates.return}T${trip.returnTime}:00`,
      carrierName: trip.airline,
    },
  ],
}));
