import type { ItineraryOption } from "./types";

export const mockTrips: ItineraryOption[] = [
  {
    id: "tenerife-prg-nov-5n",
    destination: "Tenerife",
    country: "Kanárské ostrovy",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 22,
    month: 11,
    dates: { depart: "2026-11-12", return: "2026-11-17" },
    nights: 5,
    origin: "PRG",
    totalPrice: 6890,
    currency: "CZK",
    airline: "Smartwings",
    source: "Mock",
    sourceUrl: "https://example.com/tripwise/tenerife-prg-nov",
    departureTime: "10:15",
    returnTime: "18:25",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 72,
    destinationValue: 94,
    reliability: 84,
  },
  {
    id: "gran-canaria-vie-nov-5n",
    destination: "Gran Canaria",
    country: "Kanárské ostrovy",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 23,
    month: 11,
    dates: { depart: "2026-11-08", return: "2026-11-13" },
    nights: 5,
    origin: "VIE",
    totalPrice: 6290,
    currency: "CZK",
    airline: "Ryanair",
    source: "Ryanair",
    sourceUrl: "https://www.ryanair.com/",
    departureTime: "07:50",
    returnTime: "16:40",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 76,
    destinationValue: 93,
    reliability: 86,
  },
  {
    id: "malaga-prg-nov-4n",
    destination: "Málaga",
    country: "Španělsko",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 18,
    month: 11,
    dates: { depart: "2026-11-19", return: "2026-11-23" },
    nights: 4,
    origin: "PRG",
    totalPrice: 5190,
    currency: "CZK",
    airline: "Ryanair",
    source: "Ryanair",
    sourceUrl: "https://www.ryanair.com/",
    departureTime: "09:35",
    returnTime: "17:10",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 88,
    destinationValue: 88,
    reliability: 82,
  },
  {
    id: "madeira-vie-nov-6n",
    destination: "Madeira",
    country: "Portugalsko",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 20,
    month: 11,
    dates: { depart: "2026-11-15", return: "2026-11-21" },
    nights: 6,
    origin: "VIE",
    totalPrice: 7980,
    currency: "CZK",
    airline: "Austrian + TAP",
    source: "Kiwi",
    sourceUrl: "https://www.kiwi.com/",
    departureTime: "12:40",
    returnTime: "19:00",
    baggageIncluded: ["backpack", "cabin"],
    direct: false,
    layoverHours: 2.2,
    weekendFit: 64,
    destinationValue: 92,
    reliability: 78,
  },
  {
    id: "larnaca-prg-nov-4n",
    destination: "Larnaka",
    country: "Kypr",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 21,
    month: 11,
    dates: { depart: "2026-11-05", return: "2026-11-09" },
    nights: 4,
    origin: "PRG",
    totalPrice: 5790,
    currency: "CZK",
    airline: "Wizz Air",
    source: "Skyscanner",
    sourceUrl: "https://www.skyscanner.net/",
    departureTime: "11:20",
    returnTime: "19:45",
    baggageIncluded: ["backpack", "cabin"],
    direct: true,
    weekendFit: 94,
    destinationValue: 90,
    reliability: 84,
  },
  {
    id: "malta-ped-nov-4n",
    destination: "Malta",
    country: "Malta",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 19,
    month: 11,
    dates: { depart: "2026-11-10", return: "2026-11-14" },
    nights: 4,
    origin: "PED",
    totalPrice: 8290,
    currency: "CZK",
    airline: "Ryanair + KM Malta",
    source: "Mock",
    sourceUrl: "https://example.com/tripwise/malta-ped-nov",
    departureTime: "08:10",
    returnTime: "21:50",
    baggageIncluded: ["backpack"],
    direct: false,
    layoverHours: 3.5,
    weekendFit: 70,
    destinationValue: 87,
    reliability: 70,
  },
  {
    id: "malaga-ped-nov-4n",
    destination: "Málaga",
    country: "Španělsko",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 18,
    month: 11,
    dates: { depart: "2026-11-22", return: "2026-11-26" },
    nights: 4,
    origin: "PED",
    totalPrice: 7600,
    currency: "CZK",
    airline: "Smartwings + Ryanair",
    source: "Mock",
    sourceUrl: "https://example.com/tripwise/malaga-ped-nov",
    departureTime: "13:20",
    returnTime: "20:10",
    baggageIncluded: ["backpack"],
    direct: false,
    layoverHours: 4,
    weekendFit: 63,
    destinationValue: 85,
    reliability: 68,
  },
  {
    id: "malaga-prg-jun-4n",
    destination: "Málaga",
    country: "Španělsko",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 27,
    month: 6,
    dates: { depart: "2026-06-12", return: "2026-06-16" },
    nights: 4,
    origin: "PRG",
    totalPrice: 4290,
    currency: "CZK",
    airline: "Ryanair",
    source: "Ryanair",
    sourceUrl: "https://www.ryanair.com/",
    departureTime: "09:35",
    returnTime: "17:10",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 92,
    destinationValue: 88,
    reliability: 82,
  },
  {
    id: "nice-vie-jun-3n",
    destination: "Nice",
    country: "Francie",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 25,
    month: 6,
    dates: { depart: "2026-06-05", return: "2026-06-08" },
    nights: 3,
    origin: "VIE",
    totalPrice: 5850,
    currency: "CZK",
    airline: "Wizz Air",
    source: "Skyscanner",
    sourceUrl: "https://www.skyscanner.net/",
    departureTime: "11:20",
    returnTime: "19:45",
    baggageIncluded: ["backpack", "cabin"],
    direct: true,
    weekendFit: 97,
    destinationValue: 91,
    reliability: 86,
  },
  {
    id: "split-vie-jun-4n",
    destination: "Split",
    country: "Chorvatsko",
    destinationType: "sea",
    destinationMode: "sea",
    expectedTemperatureC: 26,
    month: 6,
    dates: { depart: "2026-06-20", return: "2026-06-24" },
    nights: 4,
    origin: "VIE",
    totalPrice: 3990,
    currency: "CZK",
    airline: "Austrian",
    source: "Skyscanner",
    sourceUrl: "https://www.skyscanner.net/",
    departureTime: "05:45",
    returnTime: "14:35",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 78,
    destinationValue: 84,
    reliability: 84,
  },
  {
    id: "barcelona-prg-jun-5n",
    destination: "Barcelona",
    country: "Španělsko",
    destinationType: "cityBreak",
    destinationMode: "cityBreak",
    expectedTemperatureC: 26,
    month: 6,
    dates: { depart: "2026-06-18", return: "2026-06-23" },
    nights: 5,
    origin: "PRG",
    totalPrice: 6490,
    currency: "CZK",
    airline: "Vueling",
    source: "Kiwi",
    sourceUrl: "https://www.kiwi.com/",
    departureTime: "06:05",
    returnTime: "21:30",
    baggageIncluded: ["backpack", "cabin"],
    direct: true,
    weekendFit: 70,
    destinationValue: 90,
    reliability: 80,
  },
  {
    id: "copenhagen-prg-jun-2n",
    destination: "Kodaň",
    country: "Dánsko",
    destinationType: "cityBreak",
    destinationMode: "cityBreak",
    expectedTemperatureC: 19,
    month: 6,
    dates: { depart: "2026-06-19", return: "2026-06-21" },
    nights: 2,
    origin: "PRG",
    totalPrice: 3190,
    currency: "CZK",
    airline: "Norwegian",
    source: "Skyscanner",
    sourceUrl: "https://www.skyscanner.net/",
    departureTime: "10:15",
    returnTime: "18:25",
    baggageIncluded: ["backpack"],
    direct: true,
    weekendFit: 100,
    destinationValue: 78,
    reliability: 88,
  },
];
